import os
import logging
import sys
from typing import TYPE_CHECKING, Callable, Optional, Tuple

from gpustack.client import ClientSet
from gpustack.client.worker_manager_clients import (
    WorkerStatusClient,
    WorkerRegistrationClient,
)
from gpustack.config.config import Config
from gpustack.schemas.workers import (
    DirectProcessCapabilities,
    WorkerCreate,
    WorkerUpdate,
    WorkerRegistrationPublic,
    WorkerReachabilityCapabilities,
    WorkerReachabilityModeEnum,
)
from gpustack.schemas.config import PredefinedConfigNoDefaults
from gpustack.security import API_KEY_PREFIX
from gpustack.utils import platform
from gpustack.config.registration import (
    registration_client,
    read_worker_token,
    write_worker_token,
)
from gpustack.utils.uuid import (
    set_worker_name,
    get_worker_name,
    set_legacy_uuid,
    get_legacy_uuid,
)
from gpustack.worker.bootstrap_manager import (
    BootstrapManager,
    HostBootstrapAction,
    HostBootstrapRequest,
    HostBootstrapResult,
)

if TYPE_CHECKING:
    from gpustack.worker.collector import WorkerStatusCollector

logger = logging.getLogger(__name__)

DIRECT_PROCESS_MODE_LABEL = "gpustack.direct-process-mode"


class WorkerManager:
    _is_embedded: bool
    _collector: "WorkerStatusCollector"
    _clientset: Optional[ClientSet] = None
    _registration_client: Optional[WorkerRegistrationClient] = None
    _status_client: Optional[WorkerStatusClient] = None
    _bootstrap_manager: Optional[BootstrapManager] = None
    _capabilities_getter: Callable[[], WorkerReachabilityCapabilities]
    _reachability_mode_getter: Callable[[], WorkerReachabilityModeEnum]

    @property
    def _data_dir(self) -> str:
        data_dir = self._cfg.data_dir
        assert data_dir is not None
        return data_dir

    def __init__(
        self,
        cfg: Config,
        is_embedded: bool,
        collector: "WorkerStatusCollector",
        capabilities_getter: Callable[[], WorkerReachabilityCapabilities],
        reachability_mode_getter: Callable[[], WorkerReachabilityModeEnum],
    ):
        self._is_embedded = is_embedded
        self._cfg = cfg
        self._collector = collector
        self._capabilities_getter = capabilities_getter
        self._reachability_mode_getter = reachability_mode_getter
        worker_token = read_worker_token(self._data_dir)
        if worker_token:
            self._prepare_clients(worker_token)

    def _prepare_clients(self, token: str):
        self._clientset = ClientSet(
            base_url=self._cfg.get_server_url(),
            api_key=token,
        )
        self._status_client = WorkerStatusClient(self._clientset.http_client)

    def sync_worker_status(self):
        """
        Should be called periodically to sync the worker node status with the server.
        It registers the worker node with the server if necessary.
        """
        if self._status_client is None:
            return
        clientset = self._clientset
        if clientset is None:
            return
        try:
            workerStatus = self._collector.timed_collect(clientset)
        except Exception as e:
            logger.error(f"Failed to collect status for worker: {e}")
            return
        try:
            self._status_client.create(workerStatus)
        except Exception as e:
            logger.error(f"Failed to update worker status: {e}")

    def register_with_server(
        self,
    ) -> Tuple[ClientSet, Optional[PredefinedConfigNoDefaults]]:
        # always re-register the worker and retrive the token and config
        try:
            worker_registerred = self._register_worker()
            token = worker_registerred.token
            write_worker_token(self._data_dir, token)
            self._prepare_clients(token)
            clientset = self._clientset
            assert clientset is not None
            return clientset, worker_registerred.worker_config
        except Exception as e:
            logger.error(f"Failed to register worker: {e}")
            raise

    def _register_worker(self) -> WorkerRegistrationPublic:
        name = self._cfg.worker_name or get_worker_name(self._data_dir)
        logger.info(
            f"Registering worker with name: {name or '<auto-generated-name>'}",
        )
        if self._is_embedded:
            # always reloads the token
            self._cfg.reload_token()
        registration_client_instance = registration_client(
            data_dir=self._data_dir,
            server_url=self._cfg.get_server_url(),
            registration_token=self._cfg.token,
            wait_token_file=self._is_embedded,
        )
        assert registration_client_instance is not None
        self._registration_client = registration_client_instance
        external_id = None
        external_id_path = os.path.join(self._data_dir, 'external_id')
        if os.path.exists(external_id_path):
            with open(os.path.join(self._data_dir, 'external_id'), 'r') as f:
                external_id = f.read()

        workerStatus = self._collector.timed_collect(initial=True)
        # Set empty name if not specified to avoid validation error
        workerUpdate = WorkerUpdate(
            name=name or "",
            labels=self._ensure_builtin_labels(),
        )
        to_register = WorkerCreate.model_validate(
            {
                **workerStatus.model_dump(),
                **workerUpdate.model_dump(),
                "external_id": external_id,
                "capabilities": self._capabilities_getter().model_dump(),
                "reachability_mode": self._reachability_mode_getter().value,
            }
        )
        created = self._registration_client.create(to_register)
        logger.info(f"Worker {created.name} registered with worker_id {created.id}.")
        set_worker_name(self._data_dir, created.name)
        set_legacy_uuid(self._data_dir, created.worker_uuid)
        return created

    def _register_shutdown_hooks(self):
        pass

    def _get_bootstrap_manager(self) -> BootstrapManager:
        manager = self._bootstrap_manager
        if manager is None:
            manager = BootstrapManager(self._cfg)
            self._bootstrap_manager = manager
        return manager

    def execute_host_bootstrap(
        self,
        request: HostBootstrapRequest,
        *,
        mutate_action: Callable[[HostBootstrapAction], None] | None = None,
        dry_run: bool | None = None,
    ) -> HostBootstrapResult:
        return self._get_bootstrap_manager().execute_host_bootstrap(
            request,
            mutate_action=mutate_action,
            dry_run=dry_run,
        )

    def _ensure_builtin_labels(self) -> dict:
        labels = {
            "os": platform.system(),
            "arch": platform.arch(),
        }
        if getattr(self._cfg, "direct_process_mode", False):
            labels[DIRECT_PROCESS_MODE_LABEL] = "true"
            # Advertise per-backend direct-process capabilities so the
            # scheduler/filter layer can make fine-grained decisions.
            caps = self._build_direct_process_capabilities()
            labels.update(caps.to_labels())

        # worker name label will be set during registration
        name = self._cfg.worker_name or get_worker_name(self._data_dir)
        if name:
            labels["worker-name"] = name

        # Legacy workers with version 0.7.x send worker_uuid as part of registration.
        # Legacy workers with version <0.7.x don't have worker_uuid, so we use this label as part of the registration allowance.
        is_legacy_token = self._cfg.token and not self._cfg.token.startswith(
            API_KEY_PREFIX
        )
        is_legacy_worker = get_legacy_uuid(self._data_dir) is None
        is_existing_worker = get_worker_name(self._data_dir) is not None

        if (is_legacy_token or is_legacy_worker) and is_existing_worker:
            labels["gpustack.existence-check"] = "true"
        return labels

    def _build_direct_process_capabilities(self) -> DirectProcessCapabilities:
        """Build the direct-process capability descriptor from the registries.

        This is called only when ``direct_process_mode`` is enabled.  The
        returned object is converted to labels via ``to_labels()`` and merged
        into the worker's label set.
        """
        from gpustack.worker.direct_process import (
            _get_direct_process_backend_contracts,
            get_direct_process_distributed_backends,
            get_direct_process_supported_backends,
        )

        single_backends = sorted(get_direct_process_supported_backends())
        distributed_backends = sorted(get_direct_process_distributed_backends(self._cfg))
        bootstrap_backends = sorted(
            backend
            for backend, server_cls in _get_direct_process_backend_contracts().items()
            if backend in single_backends
            and server_cls.get_direct_process_bootstrap_recipe_id()
        )
        host_bootstrap_backends = (
            single_backends
            if getattr(self._cfg, "enable_host_bootstrap", False)
            and sys.platform.lower().startswith(
                BootstrapManager.HOST_BOOTSTRAP_SUPPORTED_PLATFORMS
            )
            else []
        )
        return DirectProcessCapabilities(
            enabled=True,
            single_worker_backends=single_backends,
            bootstrap_ready_backends=bootstrap_backends,
            distributed_backends=distributed_backends,
            host_bootstrap_backends=host_bootstrap_backends,
            custom_contract_support=True,
        )
